"""initial

Revision ID: a00948173cef
Revises: 
Create Date: 2023-08-07 17:04:24.105263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a00948173cef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('cover', sa.String(), nullable=True),
    sa.Column('singer', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lists_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('songs-in-lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_name', sa.String(), nullable=True),
    sa.Column('song_cover', sa.String(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], name=op.f('fk_songs-in-lists_list_id_lists')),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name=op.f('fk_songs-in-lists_song_id_songs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_songs-in-lists_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs-in-lists')
    op.drop_table('lists')
    op.drop_table('users')
    op.drop_table('songs')
    # ### end Alembic commands ###
